### ISSUE TITLE
Consider using Microsoft.Azure.Services.AppAuthentication for S2S calls

### ISSUE THREAD

**Issue by stansw** [Azure-Samples/digital-twins-samples-csharp#33]
Please review this article. There might be opportunity to simplify sample project and documentation.

https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication

This is how I modified sample to get it to run in the context of logged in user.

```
        private static async Task<HttpClient> SetupHttpClient(ILogger logger, AppSettings appSettings)
        {
            var httpClient = new HttpClient(new LoggingHttpHandler(logger))
            {
                BaseAddress = new Uri(appSettings.BaseUrl),
            };

            var tokenProvider = new AzureServiceTokenProvider();
            var accessToken = await tokenProvider.GetAccessTokenAsync("0b07f429-9f4b-4714-9392-cc5e8e80c8b0");

            //var accessToken = (await Authentication.GetToken(logger, appSettings));
            httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + accessToken);
            httpClient.DefaultRequestHeaders.Add("x-ms-flighting-udf-execution-manually-enabled", "true");
            return httpClient;
        }
```

@sup-s, you might be interested in this as well.

**Comment by dsk-2015** [comment]
Thank you @stansw for the suggestion. Fernando is our point of contact for engineering and he has marked this as enhancement project. The engineering team should be able to make this modification soon. 
FYI @alinamstanciu.

**Comment by alinamstanciu** [comment]
Yes, we've got this. I think anyone can do this workaround based on above code if they need to. I am planning to postpone this for now. The reason is we need to focus on vNext (GA) samples unless we hear many people need this fix.
Thank you
--Alina
