### ISSUE TITLE
Provisioning of IoT Hub resource not working in case of existence of free IoT Hub in subscription

### ISSUE THREAD

**Issue by MarekLani** [Azure-Samples/digital-twins-samples-csharp#61]
### Description
As provisionSample.yaml file does not contain size setting for IoT Hub resource,  default value of XSmall (XS) size is used during POST request to /api/v1.0/resources endpoint, which means that underlying IoT Hub resource is being created in free tier. As there is limitation of one free IoT Hub per subscription, this provisioning ends with error in case there was free IoT Hub already deployed to subscription before.

### Repro steps

Deploy free IoT Hub instances to Azure subscription and afterwards run Digital Twins provision Sample
### Expected behavior

Add and discuss option to select size of IoT Hub within sample and quickstart docs

### Known workarounds
Add size propety to ResourceDescription class + add size setting to provisionSample.yaml file in following way:
- name: Quickstart Building
  type: Venue
  resources:
  - type: IoTHub
    size: M (available option XS, S, M, L, XL, XXL)

* Operating system
N/A
* CoreCLR version (run `dotnet --version`)
N/A

**Comment by KingdomOfEnds** [comment]
Hi @MarekLani - I've looped in the dev team. Thanks!

**Comment by KingdomOfEnds** [comment]
@MarekLani - Confirming that the Swagger and Documentation will be reviewed for improved clarification. I'll close this now but feel free to comment here.
