### ISSUE TITLE
Response Status: 403, Forbidden

### ISSUE THREAD

**Issue by ANISHSINZEROTECH** [Azure-Samples/digital-twins-samples-csharp#63]
### Description

Hi, While running following command (dotnet run ProvisionSample), getting response status :-
Response Status: 403, Forbidden {"error":{"code":"403.600.000.001","message":"System error."}}

### Repro steps

Please provide the steps required to reproduce the problem.

1. dotnet run ProvisionSample

2. authenticated with azure login.
3.  error --Response Status: 403, Forbidden {"error":{"code":"403.600.000.001","message":"System error."}}
### Expected behavior

should be get connectionstring

**Comment by arjantent** [comment]
I am facing the same problem

**Comment by alinamstanciu** [comment]
Hi @ANISHSINZEROTECH and @arjantent,
 
The user which is trying this provision is not the same user that deployed the DT instance. If you are getting 403, it means you are not authorized by the system and you need higher permissions. Please ask the user which deployed the instance to create a role assignment for the user that gets 403. See article on how to create a role assignment https://docs.microsoft.com/en-us/azure/digital-twins/security-create-manage-role-assignments
For example, a "Space Administrator" role assignment on the root node can be created for user which gets 403 like following 
POST on YOUR_MANAGEMENT_API_URL/roleassignments

{
  "RoleId": "98e44ad7-28d4-4007-853b-b9968ad132d1",
  "objectId" : "<guid>",
  "objectIdType" : "UserId",
  "tenantId": "< Azure tenant id>",
  "Path": "/"
}


--Alina

**Comment by ANISHSINZEROTECH** [comment]
Thanks, Issue resolved.
